eol: handle LockUnavailable error (issue2569)
If the repository is not locked when clearing the dirstate, then
running test-eol.t in a loop fails sooner or later with:

  ERROR: /home/mg/src/mercurial-crew/tests/test-eol.t output changed
  --- /home/mg/src/mercurial-crew/tests/test-eol.t
  +++ /home/mg/src/mercurial-crew/tests/test-eol.t.err
  @@ -343,6 +343,7 @@
     % hg status (eol activated)
     M win.txt
     % hg commit
  +  nothing changed
     % hg status
     $ testmixed CRLF

However, if we cannot lock the repository, then we can also not make a
commit and so we can simply ignore a LockUnavailable error.