color: handle more Windows console errors
If your application is being built as a non-console application,
stdout is not a valid handle and raises an exception:

pywintypes.error: (6, 'DuplicateHandle', 'The handle is invalid.')

Alternatively, non-console applications launched outside of a
console will return None from GetStdHandle instead of raising an
exception.