Improve error handling in osutil.c
1) In posix part set error when path is too long so instead of

SystemError: error returned without exception set

it will raise

ValueError: path too long

2) In Win32 part replace generic

PyErr_SetExcFromWindowsErrWithFilename

by

PyErr_SetFromWindowsErrWithFilename

The exception returned is WinError(based on OSError) and
some rudimentary errno translation is performed from Windows error range
to errno module friendly range so errors like ENOENT can be handled via symbolic
constant and consistently between Win32 and Posix.